## ======================================================================
## resources
## ======================================================================

resource_types:
  - name: pull_request_with_submodule
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
  - name: gpdb_pr
    type: pull_request_with_submodule
    source:
      repo: greenplum-db/gpdb
      access_token: {{gpdb-git-access-token}}

  - name: centos-gpdb-dev-6
    type: docker-image
    source:
      repository: pivotaldata/centos-gpdb-dev
      tag: '6-gcc6.2-llvm3.7'

  - name: gpaddon_src
    type: git
    source:
      branch: {{gpaddon-git-branch}}
      private_key: {{gpaddon-git-key}}
      uri: {{gpaddon-git-remote}}

jobs:
  - name: compile_and_test_gpdb
    public: true
    max_in_flight: 4
    plan:
    - aggregate:
      - get: gpdb_pr
        trigger: true
        version: every
      - get: centos-gpdb-dev-6
      - get: gpaddon_src

    - put: gpdb_pr
      params:
        path: gpdb_pr
        status: pending

    - aggregate:
      - task: compile_gpdb_open_source_centos6
        file: gpdb_pr/concourse/tasks/compile_gpdb_open_source.yml
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
        on_failure: &pr_failure
          put: gpdb_pr
          params:
            path: gpdb_pr
            status: failure
        timeout: 30m

      - task: compile_gpdb_centos6
        file: gpdb_pr/concourse/tasks/compile_gpdb.yml
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
        on_failure: *pr_failure
        params:
          IVYREPO_HOST: {{ivyrepo_host}}
          IVYREPO_REALM: {{ivyrepo_realm}}
          IVYREPO_USER: {{ivyrepo_user}}
          IVYREPO_PASSWD: {{ivyrepo_passwd}}
          TARGET_OS: centos
          TARGET_OS_VERSION: 6
          BLD_TARGETS: "clients loaders"

    - aggregate:
      - task: icw_planner_centos6
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=off' installcheck-world
          BLDWRAP_POSTGRES_CONF_ADDONS: "fsync=off"
          TEST_OS: centos
        timeout: 1h
        on_failure: *pr_failure

      - task: icw_gporca_orca_centos6
        file: gpdb_pr/concourse/tasks/ic_gpdb.yml
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=on' installcheck-world
          BLDWRAP_POSTGRES_CONF_ADDONS: "fsync=off"
          TEST_OS: centos
        timeout: 2h30m
        on_failure: *pr_failure

      - task: MU_check_centos
        file: gpdb_pr/concourse/tasks/gpMgmt_check_gpdb.yml
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          TEST_OS: centos
        timeout: 10m
        on_failure: *pr_failure

      - task: gpperfmon
        file: gpdb_pr/concourse/tasks/behave_gpdb.yml
        image: centos-gpdb-dev-6
        input_mapping:
          gpdb_src: gpdb_pr
          bin_gpdb: gpdb_artifacts
        params:
          BEHAVE_TAGS: gpperfmon
          BLDWRAP_POSTGRES_CONF_ADDONS: ""
        timeout: 20m
        on_failure: *pr_failure

    - task: separate_qautils_files_for_rc
      file: gpdb_pr/concourse/tasks/separate_qautils_files_for_rc.yml
      image: centos-gpdb-dev-6
      input_mapping:
        gpdb_src: gpdb_pr
        bin_gpdb: gpdb_artifacts
      params:
        QAUTILS_TARBALL: rc_bin_gpdb/QAUtils-rhel6-x86_64.tar.gz
      on_failure: *pr_failure

    - task: gpdb_rc_packaging_centos
      file: gpdb_pr/concourse/tasks/gpdb_packaging.yml
      image: centos-gpdb-dev-6
      input_mapping:
        bin_gpdb: rc_bin_gpdb
        gpdb_src: gpdb_pr
      output_mapping:
        packaged_gpdb: packaged_gpdb_rc
      params:
        INSTALL_SCRIPT_SRC: gpdb_src/gpAux/addon/license/installer-header-rhel-gpdb.sh
        INSTALLER_ZIP: packaged_gpdb/greenplum-db-@GP_VERSION@-build-1-rhel6-x86_64.zip
        ADD_README_INSTALL: true
      timeout: 15m
      on_failure: *pr_failure

    - put: report_pr_success
      resource: gpdb_pr
      params:
        path: gpdb_pr
        status: success
